INSERT INTO public.question (enonce) VALUES ( 'Sur le territoire de quel pays pouvait-on trouver les Aztèques ?');
INSERT INTO public.question (enonce) VALUES ( 'De quel courant philosophique Plotin est-il le grand représentant ?');
INSERT INTO public.question (enonce) VALUES ( 'Qui a réalisé le film « In the mood for love » ?');
INSERT INTO public.question (enonce) VALUES ( 'Parmi les hommes politiques suivants, lequel a succédé à Hugo Chavez en tant que Président du Venezuela ?');
INSERT INTO public.question (enonce) VALUES ( 'En solfège, comment appelle-t-on le silence qui dure un temps ?');
INSERT INTO public.question (enonce) VALUES ( 'Quelle année retient-on habituellement comme l’année de la chute de l’Empire romain d’Occident ?');
INSERT INTO public.question (enonce) VALUES ( 'En 2014, quelle entreprise rachète la branche énergie d’Alstom ?');
INSERT INTO public.question (enonce) VALUES ( 'Quelle race d’animal est un briard ?');
INSERT INTO public.question (enonce) VALUES ( 'On dit qu’un taureau…');
INSERT INTO public.question (enonce) VALUES ( 'De l’œuvre de quel écrivain est tirée la célèbre question (enonce) « Que sais-je ?');

INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Brésil', 1);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Mexique', 1);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Argentine', 1);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'L''aristotélisme', 2);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Le néoplatonisme', 2);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Le scepticisme', 2);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Zhang Yimou', 3);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Chan Feng Zhao', 3);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Wong Kar-Wai', 3);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Evo Morales', 4);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Nicolas Maduro', 4);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Lula', 4);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Une pause', 5);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Un silence', 5);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Un silence', 5);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, '476 ap. J.-C', 6);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, '375 ap. J.-C', 6);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, '496 ap. J.-C', 6);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Siemens', 7);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Philipps', 7);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'General Electrics', 7);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Un chien', 8);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Un cheval', 8);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Un canard', 8);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'beugle', 9);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'barète', 9);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'clabaude', 9);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Étienne de la Boétie', 10);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( false, 'Voltaire', 10);
INSERT INTO public.choix (bon_choix, designation, question_id) VALUES ( true, 'Montaigne', 10);